### ISSUE TITLE
Replace the ABIs by pulling them directly from the npm packages 

### ISSUE THREAD

**Issue by scorpion9979** [hifi-finance/hifi-subgraph#4]
Replace `abis/` folder by [@hifi/protocol](https://www.npmjs.com/package/@hifi/protocol) and [@hifi/amm](https://www.npmjs.com/package/@hifi/amm) npm packages once the sol 0.8.4 custom error issues with The Graph are resolved.

Update: this is stale until https://github.com/graphprotocol/graph-node/issues/2577 is resolved.
Update: this is no longer stale, as https://github.com/graphprotocol/graph-node/issues/2577 is now resolved

**Comment by scorpion9979** [comment]
@paulrberg  I just noticed that this issue would be a bit tricky to tackle as subgraph.yaml expects the ABIs to be json files, while our npm repos only expose the ABIs as part of the generated Typechain contract factories. I believe a solution to this would need to implement a script to pull the ABIs from those contract factories and place them into their own separate json files in a git-ignored directory, but I don't think the cost-benefit would be high enough to warrant that change.

**Comment by PaulRBerg** [comment]
You're right, the cost is not worth the benefit. I think at the time of opening this issue, the ABIs were distributed as JSON files as well. But in the meantime, we switched to TypeChain factories only.

I'll close this for now. If the maintenance cost becomes so high in this repository that automating the ABIs would be worth it, we'll re-examine this issue then.
